#ifndef DIO_PRIVATE_H
#define DIO_PRIVATE_H

#define CNFMODE0_CLEAR  0xFFFFFFF0
#define CNFMODE1_CLEAR  0xFFFFFF0F
#define CNFMODE2_CLEAR  0XFFFFF0FF
#define CNFMODE3_CLEAR  0XFFFF0FFF
#define CNFMODE4_CLEAR  0XFFF0FFFF
#define CNFMODE5_CLEAR  0XFF0FFFFF
#define CNFMODE6_CLEAR  0XF0FFFFFF
#define CNFMODE7_CLEAR  0X0FFFFFFF

#define CNFMODE8_CLEAR  0xFFFFFFF0
#define CNFMODE9_CLEAR  0xFFFFFF0F
#define CNFMODE10_CLEAR 0XFFFFF0FF
#define CNFMODE11_CLEAR 0XFFFF0FFF
#define CNFMODE12_CLEAR 0XFFF0FFFF
#define CNFMODE13_CLEAR 0XFF0FFFFF
#define CNFMODE14_CLEAR 0XF0FFFFFF
#define CNFMODE15_CLEAR 0X0FFFFFFF

#endif
